/**
 * Capturer Tier 1 — Configuración
 * Definiciones de indicadores, tipos y mapeo de ejes temáticos.
 */

// ─── Tipos ────────────────────────────────────────────────────────

export interface CapturaResult {
  slug: string
  valor: number
  valorTexto: string
  confiable: boolean
  fecha: Date
  metadata: string
  error?: string
}

// ─── Indicadores Tier 1 configuración ─────────────────────────────

export const INDICADORES_TIER1 = [
  {
    slug: 'tc-oficial-bcb',
    nombre: 'Tipo de Cambio Oficial (Venta)',
    categoria: 'monetario',
    fuente: 'Banco Central de Bolivia',
    url: 'https://www.bcb.gob.bo/?q=cotizaciones_tc',
    periodicidad: 'diaria',
    unidad: 'Bs/USD',
    formatoNumero: 2,
    tier: 1,
  },
  {
    slug: 'tc-oficial-compra',
    nombre: 'Tipo de Cambio Oficial (Compra)',
    categoria: 'monetario',
    fuente: 'Banco Central de Bolivia',
    url: 'https://www.bcb.gob.bo/?q=cotizaciones_tc',
    periodicidad: 'diaria',
    unidad: 'Bs/USD',
    formatoNumero: 2,
    tier: 1,
  },
  {
    slug: 'tc-paralelo-venta',
    nombre: 'Valor Referencial USD (Venta)',
    categoria: 'monetario',
    fuente: 'Banco Central de Bolivia',
    url: 'https://www.bcb.gob.bo/?q=cotizaciones_tc',
    periodicidad: 'diaria',
    unidad: 'Bs/USD',
    formatoNumero: 2,
    tier: 1,
  },
  {
    slug: 'tc-paralelo-compra',
    nombre: 'Valor Referencial USD (Compra)',
    categoria: 'monetario',
    fuente: 'Banco Central de Bolivia',
    url: 'https://www.bcb.gob.bo/?q=cotizaciones_tc',
    periodicidad: 'diaria',
    unidad: 'Bs/USD',
    formatoNumero: 2,
    tier: 1,
  },
  // Divisas internacionales — directamente del BCB en Bs (sin multiplicar)
  {
    slug: 'fx-eur-usd',
    nombre: 'Euro (en Bolivianos)',
    categoria: 'monetario',
    fuente: 'Banco Central de Bolivia',
    url: 'https://www.bcb.gob.bo/?q=cotizaciones_tc',
    periodicidad: 'diaria',
    unidad: 'Bs/EUR',
    formatoNumero: 2,
    tier: 1,
  },
  {
    slug: 'fx-cny-usd',
    nombre: 'Yuan (en Bolivianos)',
    categoria: 'monetario',
    fuente: 'Banco Central de Bolivia',
    url: 'https://www.bcb.gob.bo/?q=cotizaciones_tc',
    periodicidad: 'diaria',
    unidad: 'Bs/CNY',
    formatoNumero: 2,
    tier: 1,
  },
  {
    slug: 'fx-brl-usd',
    nombre: 'Real Brasileño (en Bolivianos)',
    categoria: 'monetario',
    fuente: 'Banco Central de Bolivia',
    url: 'https://www.bcb.gob.bo/?q=cotizaciones_tc',
    periodicidad: 'diaria',
    unidad: 'Bs/BRL',
    formatoNumero: 2,
    tier: 1,
  },
  {
    slug: 'fx-pen-usd',
    nombre: 'Sol Peruano (en Bolivianos)',
    categoria: 'monetario',
    fuente: 'Banco Central de Bolivia',
    url: 'https://www.bcb.gob.bo/?q=cotizaciones_tc',
    periodicidad: 'diaria',
    unidad: 'Bs/PEN',
    formatoNumero: 2,
    tier: 1,
  },
  {
    slug: 'fx-clp-usd',
    nombre: 'Peso Chileno (en Bolivianos)',
    categoria: 'monetario',
    fuente: 'Banco Central de Bolivia',
    url: 'https://www.bcb.gob.bo/?q=cotizaciones_tc',
    periodicidad: 'diaria',
    unidad: 'Bs/CLP',
    formatoNumero: 5,
    tier: 1,
  },
  {
    slug: 'fx-ars-usd',
    nombre: 'Peso Argentino (en Bolivianos)',
    categoria: 'monetario',
    fuente: 'Banco Central de Bolivia',
    url: 'https://www.bcb.gob.bo/?q=cotizaciones_tc',
    periodicidad: 'diaria',
    unidad: 'Bs/ARS',
    formatoNumero: 5,
    tier: 1,
  },
  {
    slug: 'fx-pyg-usd',
    nombre: 'Guaraní Paraguayo (en Bolivianos)',
    categoria: 'monetario',
    fuente: 'Banco Central de Bolivia',
    url: 'https://www.bcb.gob.bo/?q=cotizaciones_tc',
    periodicidad: 'diaria',
    unidad: 'Bs/PYG',
    formatoNumero: 5,
    tier: 1,
  },
  {
    slug: 'fx-jpy-usd',
    nombre: 'Yen Japonés (en Bolivianos)',
    categoria: 'monetario',
    fuente: 'Banco Central de Bolivia',
    url: 'https://www.bcb.gob.bo/?q=cotizaciones_tc',
    periodicidad: 'diaria',
    unidad: 'Bs/JPY',
    formatoNumero: 4,
    tier: 1,
  },

  // ─── Datos macro adicionales del BCB ─────────────────────
  {
    slug: 'macro-sofr-bcb',
    nombre: 'Tasa SOFR',
    categoria: 'macro_bcb',
    fuente: 'Banco Central de Bolivia',
    url: 'https://www.bcb.gob.bo/?q=cotizaciones_tc',
    periodicidad: 'diaria',
    unidad: '% anual',
    formatoNumero: 2,
    tier: 1,
  },
  {
    slug: 'macro-ufv-bcb',
    nombre: 'Unidad de Fomento de Vivienda (UFV)',
    categoria: 'macro_bcb',
    fuente: 'Banco Central de Bolivia',
    url: 'https://www.bcb.gob.bo/?q=cotizaciones_tc',
    periodicidad: 'diaria',
    unidad: 'Bs/UFV',
    formatoNumero: 5,
    tier: 1,
  },
  // Minerales — Oro y Plata del BCB (fuente oficial)
  {
    slug: 'com-oro-bcb',
    nombre: 'Oro (BCB)',
    categoria: 'minero',
    fuente: 'Banco Central de Bolivia',
    url: 'https://www.bcb.gob.bo/?q=cotizaciones_tc',
    periodicidad: 'diaria',
    unidad: 'USD/oz',
    formatoNumero: 2,
    tier: 1,
  },
  {
    slug: 'com-plata-bcb',
    nombre: 'Plata (BCB)',
    categoria: 'minero',
    fuente: 'Banco Central de Bolivia',
    url: 'https://www.bcb.gob.bo/?q=cotizaciones_tc',
    periodicidad: 'diaria',
    unidad: 'USD/oz',
    formatoNumero: 3,
    tier: 1,
  },
  // Minerales adicionales (Yahoo Finance)
  {
    slug: 'com-oro',
    nombre: 'Oro (COMEX)',
    categoria: 'minero',
    fuente: 'Yahoo Finance (Oro COMEX)',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/GC=F?interval=1d&range=2d',
    periodicidad: 'diaria',
    unidad: 'USD/oz',
    formatoNumero: 2,
    tier: 1,
  },
  {
    slug: 'com-litio',
    nombre: 'Litio (Carbonato, China)',
    categoria: 'minero',
    fuente: 'Yahoo Finance (Lithium Americas)',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/LTHM?interval=1d&range=2d',
    periodicidad: 'diaria',
    unidad: 'USD',
    formatoNumero: 2,
    tier: 1,
  },
  {
    slug: 'com-tierras-raras',
    nombre: 'Tierras Raras (ETF)',
    categoria: 'minero',
    fuente: 'Yahoo Finance (REMX)',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/REMX?interval=1d&range=2d',
    periodicidad: 'diaria',
    unidad: 'USD',
    formatoNumero: 2,
    tier: 1,
  },

  {
    slug: 'lme-cobre',
    nombre: 'LME Cobre',
    categoria: 'minero',
    fuente: 'London Metal Exchange',
    url: 'https://www.lme.com/en/metals/non-ferrous/copper',
    periodicidad: 'diaria',
    unidad: 'USD/ton',
    formatoNumero: 2,
    tier: 1,
  },
  {
    slug: 'lme-zinc',
    nombre: 'LME Zinc',
    categoria: 'minero',
    fuente: 'London Metal Exchange',
    url: 'https://www.lme.com/en/metals/non-ferrous/zinc',
    periodicidad: 'diaria',
    unidad: 'USD/ton',
    formatoNumero: 2,
    tier: 1,
  },
  {
    slug: 'lme-estano',
    nombre: 'LME Estano',
    categoria: 'minero',
    fuente: 'London Metal Exchange',
    url: 'https://www.lme.com/en/metals/non-ferrous/tin',
    periodicidad: 'diaria',
    unidad: 'USD/ton',
    formatoNumero: 2,
    tier: 1,
  },
  {
    slug: 'lme-plata',
    nombre: 'LME Plata',
    categoria: 'minero',
    fuente: 'London Metal Exchange',
    url: 'https://www.lme.com/en/metals/precious-metals/silver',
    periodicidad: 'diaria',
    unidad: 'USD/ton',
    formatoNumero: 2,
    tier: 1,
  },
  {
    slug: 'lme-plomo',
    nombre: 'LME Plomo',
    categoria: 'minero',
    fuente: 'London Metal Exchange',
    url: 'https://www.lme.com/en/metals/non-ferrous/lead',
    periodicidad: 'diaria',
    unidad: 'USD/ton',
    formatoNumero: 2,
    tier: 1,
  },
  // ─── Tier 1: Productos Agrícolas ──────────────────────
  {
    slug: 'agr-cafe',
    nombre: 'Café (Internacional)',
    categoria: 'agricolas',
    fuente: 'Yahoo Finance (Café ICE)',
    url: 'https://www.investing.com/commodities/coffee',
    periodicidad: 'diaria',
    unidad: 'USc/lb',
    formatoNumero: 2,
    tier: 1,
  },
  {
    slug: 'agr-quinua',
    nombre: 'Quinua (Mercado Internacional)',
    categoria: 'agricolas',
    fuente: 'FAO / Mercado local',
    url: '',
    periodicidad: 'semanal',
    unidad: 'USD/ton',
    formatoNumero: 0,
    tier: 2,
  },
  {
    slug: 'agr-soya',
    nombre: 'Soya (Internacional)',
    categoria: 'agricolas',
    fuente: 'Yahoo Finance (Soya CBOT)',
    url: 'https://www.investing.com/commodities/soybeans',
    periodicidad: 'diaria',
    unidad: 'USc/fanega',
    formatoNumero: 2,
    tier: 1,
  },
  {
    slug: 'agr-arroz',
    nombre: 'Arroz (Internacional)',
    categoria: 'agricolas',
    fuente: 'Yahoo Finance (Arroz CBOT)',
    url: 'https://www.investing.com/commodities/rice',
    periodicidad: 'diaria',
    unidad: 'USD/quintal',
    formatoNumero: 2,
    tier: 1,
  },
  {
    slug: 'agr-azucar',
    nombre: 'Azúcar (Internacional)',
    categoria: 'agricolas',
    fuente: 'Yahoo Finance (Azúcar ICE)',
    url: 'https://www.investing.com/commodities/sugar',
    periodicidad: 'diaria',
    unidad: 'USc/lb',
    formatoNumero: 2,
    tier: 1,
  },
  {
    slug: 'agr-maiz',
    nombre: 'Maíz (Internacional)',
    categoria: 'agricolas',
    fuente: 'Yahoo Finance (Maíz CBOT)',
    url: 'https://www.investing.com/commodities/corn',
    periodicidad: 'diaria',
    unidad: 'USc/bushel',
    formatoNumero: 2,
    tier: 1,
  },
  {
    slug: 'agr-trigo',
    nombre: 'Trigo (Internacional)',
    categoria: 'agricolas',
    fuente: 'Yahoo Finance (Trigo CBOT)',
    url: 'https://www.investing.com/commodities/wheat',
    periodicidad: 'diaria',
    unidad: 'USc/fanega',
    formatoNumero: 2,
    tier: 1,
  },
  // ─── Tier 1: Macroeconomía BCB ──────────────────────
  {
    slug: 'macro-riesgo-pais',
    nombre: 'Riesgo País (EMBI)',
    categoria: 'macro_bcb',
    fuente: 'JP Morgan / Investing.com',
    url: 'https://www.investing.com/indices/embi-plus-bolivia',
    periodicidad: 'diaria',
    unidad: 'bps',
    formatoNumero: 0,
    tier: 2,
  },
  {
    slug: 'macro-deuda-publica',
    nombre: 'Deuda Pública / PIB',
    categoria: 'macro_bcb',
    fuente: 'Banco Central de Bolivia',
    url: 'https://www.bcb.gob.bo',
    periodicidad: 'trimestral',
    unidad: '% PIB',
    formatoNumero: 1,
    tier: 2,
  },
  {
    slug: 'macro-pib',
    nombre: 'Producto Interno Bruto',
    categoria: 'macro_bcb',
    fuente: 'Banco Central de Bolivia',
    url: 'https://www.bcb.gob.bo/?q=estadisticas/pib',
    periodicidad: 'trimestral',
    unidad: 'MM USD',
    formatoNumero: 1,
    tier: 2,
  },
  {
    slug: 'macro-balanza-comercial',
    nombre: 'Balanza Comercial',
    categoria: 'macro_bcb',
    fuente: 'Banco Central de Bolivia',
    url: 'https://www.bcb.gob.bo/?q=estadisticas/balanza',
    periodicidad: 'mensual',
    unidad: 'MM USD',
    formatoNumero: 1,
    tier: 2,
  },
  // ─── INE ──────────────────────────────────────
  {
    slug: 'ine-poblacion',
    nombre: 'Población Estimada',
    categoria: 'ine',
    fuente: 'Instituto Nacional de Estadística (INE)',
    url: 'https://www.ine.gob.bo',
    periodicidad: 'anual',
    unidad: 'habitantes',
    formatoNumero: 0,
    tier: 3,
  },
  {
    slug: 'ine-pobreza',
    nombre: 'Tasa de Pobreza Extrema',
    categoria: 'ine',
    fuente: 'Instituto Nacional de Estadística (INE)',
    url: 'https://www.ine.gob.bo',
    periodicidad: 'anual',
    unidad: '%',
    formatoNumero: 1,
    tier: 3,
  },
  {
    slug: 'ine-empleo',
    nombre: 'Tasa de Empleo Adecuado',
    categoria: 'ine',
    fuente: 'Instituto Nacional de Estadística (INE)',
    url: 'https://www.ine.gob.bo',
    periodicidad: 'trimestral',
    unidad: '%',
    formatoNumero: 1,
    tier: 3,
  },
  {
    slug: 'ine-pib-departamental',
    nombre: 'PIB Departamental',
    categoria: 'ine',
    fuente: 'Instituto Nacional de Estadística (INE)',
    url: 'https://www.ine.gob.bo',
    periodicidad: 'anual',
    unidad: 'MM USD',
    formatoNumero: 1,
    tier: 3,
  },
  // ─── Salud ──────────────────────────────────────
  {
    slug: 'salud-desnutricion',
    nombre: 'Desnutrición Crónica (< 5 años)',
    categoria: 'salud',
    fuente: 'Ministerio de Salud y Deportes / ENDSA',
    url: 'https://www.minsalud.gob.bo',
    periodicidad: 'anual',
    unidad: '%',
    formatoNumero: 1,
    tier: 3,
  },
  {
    slug: 'salud-materna',
    nombre: 'Mortalidad Materna',
    categoria: 'salud',
    fuente: 'Ministerio de Salud y Deportes / ENDSA',
    url: 'https://www.minsalud.gob.bo',
    periodicidad: 'anual',
    unidad: 'x 100,000 nv',
    formatoNumero: 0,
    tier: 3,
  },
  {
    slug: 'salud-esperanza-vida',
    nombre: 'Esperanza de Vida al Nacer',
    categoria: 'salud',
    fuente: 'Instituto Nacional de Estadística (INE) / ENDSA',
    url: 'https://www.ine.gob.bo',
    periodicidad: 'anual',
    unidad: 'años',
    formatoNumero: 1,
    tier: 3,
  },
  // ─── Tier 2: Indicadores de Conflictividad ──────────────────────
  {
    slug: 'conflictividad-tns',
    nombre: 'Índice de Tensión Social',
    categoria: 'social',
    fuente: 'ONION200 (análisis de menciones)',
    url: '',
    periodicidad: 'diaria',
    unidad: 'escala 1-10',
    formatoNumero: 1,
    tier: 2,
  },
  {
    slug: 'conflictividad-bloqueos',
    nombre: 'Bloqueos / Marchas Activas',
    categoria: 'social',
    fuente: 'ONION200 (análisis de menciones)',
    url: '',
    periodicidad: 'diaria',
    unidad: 'eventos',
    formatoNumero: 0,
    tier: 2,
  },
  {
    slug: 'conflictividad-puntos',
    nombre: 'Puntos de Conflicto',
    categoria: 'social',
    fuente: 'ONION200 (análisis de menciones)',
    url: '',
    periodicidad: 'diaria',
    unidad: 'puntos',
    formatoNumero: 0,
    tier: 2,
  },
  {
    slug: 'conflictividad-escalamiento',
    nombre: 'Nivel de Escalamiento',
    categoria: 'social',
    fuente: 'ONION200 (evaluación general)',
    url: '',
    periodicidad: 'diaria',
    unidad: 'categoría',
    formatoNumero: 0,
    tier: 2,
  },
  // ─── Minería Boliviana ──────────────────────────────────────
  {
    slug: 'mineria-produccion-tm',
    nombre: 'Producción Minera (TMF)',
    categoria: 'minero',
    fuente: 'Servicio Nacional de Registro y Control de la Comercialización de Minerales y Metales (SENARECOM)',
    url: 'https://senarecom.gob.bo',
    periodicidad: 'mensual',
    unidad: 'TMF',
    formatoNumero: 0,
    tier: 2,
  },
  {
    slug: 'mineria-exportaciones-fob',
    nombre: 'Exportaciones Mineras FOB',
    categoria: 'minero',
    fuente: 'Instituto Nacional de Estadística (INE)',
    url: 'https://www.ine.gob.bo',
    periodicidad: 'mensual',
    unidad: 'USD millones',
    formatoNumero: 1,
    tier: 2,
  },

  {
    slug: 'mineria-precio-litio',
    nombre: 'Precio Carbonato de Litio',
    categoria: 'minero',
    fuente: 'Benchmark Mineral Intelligence',
    url: 'https://www.benchmarkminerals.com',
    periodicidad: 'semanal',
    unidad: 'USD/ton',
    formatoNumero: 0,
    tier: 2,
  },
  {
    slug: 'mineria-litio-ylb',
    nombre: 'Avance Proyecto YLB EV Metals',
    categoria: 'minero',
    fuente: 'Yacimientos de Litio Bolivianos (YLB)',
    url: 'https://www.ylb.gob.bo',
    periodicidad: 'trimestral',
    unidad: '% avance',
    formatoNumero: 1,
    tier: 3,
  },
  {
    slug: 'mineria-conflictividad-cooperativas',
    nombre: 'Conflictividad Minera (Cooperativas)',
    categoria: 'social',
    fuente: 'ONION200 (análisis de menciones)',
    url: '',
    periodicidad: 'diaria',
    unidad: 'eventos',
    formatoNumero: 0,
    tier: 2,
  },
  {
    slug: 'mineria-pasivos-ambientales',
    nombre: 'Pasivos Ambientales Mineros',
    categoria: 'minero',
    fuente: 'Ministerio de Medio Ambiente y Agua',
    url: 'https://www.mmaya.gob.bo',
    periodicidad: 'anual',
    unidad: 'sitios',
    formatoNumero: 0,
    tier: 3,
  },
  {
    slug: 'mineria-regalias-recaudacion',
    nombre: 'Recaudación Regalías Mineras',
    categoria: 'economico',
    fuente: 'Ministerio de Minería y Metalurgia',
    url: 'https://www.mineria.gob.bo',
    periodicidad: 'mensual',
    unidad: 'Bs millones',
    formatoNumero: 1,
    tier: 2,
  },
  {
    slug: 'mineria-dias-perdidos-paros',
    nombre: 'Días Perdidos por Paros Mineros',
    categoria: 'social',
    fuente: 'ONION200 (análisis de menciones)',
    url: '',
    periodicidad: 'semanal',
    unidad: 'días',
    formatoNumero: 0,
    tier: 2,
  },
  // ─── Tier 1: Energéticos ──────────────────────
  {
    slug: 'nrg-petroleo',
    nombre: 'Petróleo Crudo (WTI)',
    categoria: 'energetico',
    fuente: 'Yahoo Finance (Petróleo WTI)',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/CL=F?interval=1d&range=2d',
    periodicidad: 'diaria',
    unidad: 'USD/bbl',
    formatoNumero: 2,
    tier: 1,
  },
  {
    slug: 'nrg-gas-natural',
    nombre: 'Gas Natural (Henry Hub)',
    categoria: 'energetico',
    fuente: 'Yahoo Finance (Gas Natural)',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/NG=F?interval=1d&range=2d',
    periodicidad: 'diaria',
    unidad: 'USD/MMBtu',
    formatoNumero: 2,
    tier: 1,
  },
  {
    slug: 'nrg-gasolina',
    nombre: 'Gasolina (RBOB)',
    categoria: 'energetico',
    fuente: 'Yahoo Finance (Gasolina RBOB)',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/RB=F?interval=1d&range=2d',
    periodicidad: 'diaria',
    unidad: 'USD/gal',
    formatoNumero: 2,
    tier: 1,
  },
  {
    slug: 'nrg-diesel',
    nombre: 'Diésel (Aceite de Calefacción)',
    categoria: 'energetico',
    fuente: 'Yahoo Finance (Aceite de Calefacción)',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/HO=F?interval=1d&range=2d',
    periodicidad: 'diaria',
    unidad: 'USD/gal',
    formatoNumero: 2,
    tier: 1,
  },
  {
    slug: 'nrg-glp',
    nombre: 'GLP (Propano)',
    categoria: 'energetico',
    fuente: 'Yahoo Finance (Propano)',
    url: 'https://query1.finance.yahoo.com/v8/finance/chart/PL=F?interval=1d&range=2d',
    periodicidad: 'diaria',
    unidad: 'USD/gal',
    formatoNumero: 2,
    tier: 1,
  },
]

// ─── Mapping indicador → ejes temáticos ──────────────────────────

export function getEjesForIndicador(slug: string): string {
  const mapping: Record<string, string> = {
    'tc-oficial-bcb': 'economia,hidrocarburos,relaciones-internacionales',
    'tc-oficial-compra': 'economia,hidrocarburos,relaciones-internacionales',
    'tc-paralelo-venta': 'economia,hidrocarburos,relaciones-internacionales',
    'tc-paralelo-compra': 'economia,hidrocarburos,relaciones-internacionales',
    'fx-eur-usd': 'economia,relaciones-internacionales',
    'fx-cny-usd': 'economia,relaciones-internacionales',
    'fx-brl-usd': 'economia,relaciones-internacionales',
    'fx-pen-usd': 'economia,relaciones-internacionales',
    'fx-clp-usd': 'economia,relaciones-internacionales',
    'fx-ars-usd': 'economia,relaciones-internacionales',
    'fx-pyg-usd': 'economia,relaciones-internacionales',
    'fx-jpy-usd': 'economia,relaciones-internacionales,mineria',
    'fx-gbp-usd': 'economia,relaciones-internacionales',
    'fx-chf-usd': 'economia,relaciones-internacionales',
    'com-oro': 'mineria,economia,hidrocarburos-energia',
    'com-oro-bcb': 'mineria,economia,hidrocarburos-energia',
    'com-plata-bcb': 'mineria,economia',
    'com-litio': 'mineria,hidrocarburos-energia,relaciones-internacionales',
    'com-tierras-raras': 'mineria,medio-ambiente,relaciones-internacionales',
    'nrg-petroleo': 'hidrocarburos-energia,economia,relaciones-internacionales',
    'nrg-gas-natural': 'hidrocarburos-energia,economia',
    'nrg-gasolina': 'hidrocarburos-energia,economia',
    'nrg-diesel': 'hidrocarburos-energia,economia',
    'nrg-glp': 'hidrocarburos-energia,economia',

    'lme-cobre': 'medio-ambiente,economia',
    'lme-zinc': 'medio-ambiente,economia',
    'lme-estano': 'medio-ambiente,economia',
    'lme-plata': 'medio-ambiente,economia',
    'lme-plomo': 'medio-ambiente,economia',
    'conflictividad-tns': 'movimientos-sociales,gobierno-oposicion,corrupcion-impunidad',
    'conflictividad-bloqueos': 'movimientos-sociales,educacion-cultura,salud-servicios',
    'conflictividad-puntos': 'movimientos-sociales,gobierno-oposicion',
    'conflictividad-escalamiento': 'movimientos-sociales,gobierno-oposicion,procesos-electorales',
    // Minería Boliviana
    'mineria-produccion-tm': 'mineria,economia,hidrocarburos-energia',
    'mineria-exportaciones-fob': 'mineria,economia,relaciones-internacionales',

    'mineria-precio-litio': 'mineria,hidrocarburos-energia,relaciones-internacionales',
    'mineria-litio-ylb': 'mineria,gobierno-oposicion,hidrocarburos-energia',
    'mineria-conflictividad-cooperativas': 'mineria,movimientos-sociales,justicia-derechos',
    'mineria-pasivos-ambientales': 'mineria,medio-ambiente',
    'mineria-regalias-recaudacion': 'mineria,economia,gobierno-oposicion',
    'mineria-dias-perdidos-paros': 'mineria,movimientos-sociales',
    // Productos Agrícolas
    'agr-cafe': 'economia,relaciones-internacionales',
    'agr-quinua': 'economia,medio-ambiente',
    'agr-soya': 'economia,hidrocarburos-energia,relaciones-internacionales',
    'agr-arroz': 'economia,medio-ambiente',
    'agr-azucar': 'economia,relaciones-internacionales',
    'agr-maiz': 'economia,medio-ambiente',
    'agr-trigo': 'economia,relaciones-internacionales',
    // Macroeconomía BCB

    'macro-riesgo-pais': 'economia,relaciones-internacionales,gobierno-oposicion',
    'macro-deuda-publica': 'economia,gobierno-oposicion',
    'macro-pib': 'economia,relaciones-internacionales',
    'macro-balanza-comercial': 'economia,relaciones-internacionales,hidrocarburos-energia',
    // INE
    'ine-poblacion': 'justicia-derechos,salud-servicios',
    'ine-pobreza': 'justicia-derechos,gobierno-oposicion',
    'ine-empleo': 'economia,justicia-derechos',
    'ine-pib-departamental': 'economia',
    // Salud
    'salud-desnutricion': 'salud-servicios,justicia-derechos,gobierno-oposicion',
    'salud-materna': 'salud-servicios,justicia-derechos',
    'salud-esperanza-vida': 'salud-servicios,justicia-derechos',
  }
  return mapping[slug] ?? ''
}
