
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('@prisma/client/runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state'
};

exports.Prisma.AdminFeedbackScalarFieldEnum = {
  id: 'id',
  tipo: 'tipo',
  instruccionOriginal: 'instruccionOriginal',
  resultado: 'resultado',
  accionEjecutada: 'accionEjecutada',
  detalle: 'detalle',
  productoAfectado: 'productoAfectado',
  sugerenciaGenerada: 'sugerenciaGenerada',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AprendizajeSistemaScalarFieldEnum = {
  id: 'id',
  modulo: 'modulo',
  medioId: 'medioId',
  ejeTematicoId: 'ejeTematicoId',
  personaId: 'personaId',
  keywordPropuesta: 'keywordPropuesta',
  actorPropuesto: 'actorPropuesto',
  tipoDato: 'tipoDato',
  datoActual: 'datoActual',
  datoOptimo: 'datoOptimo',
  confianza: 'confianza',
  impacto: 'impacto',
  estado: 'estado',
  aplicadaEn: 'aplicadaEn',
  origen: 'origen',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CapturaLogScalarFieldEnum = {
  id: 'id',
  fecha: 'fecha',
  medioId: 'medioId',
  nivel: 'nivel',
  totalArticulos: 'totalArticulos',
  mencionesEncontradas: 'mencionesEncontradas',
  exitosa: 'exitosa',
  errores: 'errores'
};

exports.Prisma.ClienteScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  nombreContacto: 'nombreContacto',
  email: 'email',
  telefono: 'telefono',
  whatsapp: 'whatsapp',
  organizacion: 'organizacion',
  segmento: 'segmento',
  plan: 'plan',
  estado: 'estado',
  parlamentarios: 'parlamentarios',
  ejesContratados: 'ejesContratados',
  notas: 'notas',
  ci: 'ci',
  razonSocial: 'razonSocial',
  nit: 'nit',
  fechaCreacion: 'fechaCreacion',
  fechaActualizacion: 'fechaActualizacion'
};

exports.Prisma.ComentarioScalarFieldEnum = {
  id: 'id',
  mencionId: 'mencionId',
  autor: 'autor',
  texto: 'texto',
  sentimiento: 'sentimiento',
  fechaComentario: 'fechaComentario',
  fechaCaptura: 'fechaCaptura'
};

exports.Prisma.ContratoScalarFieldEnum = {
  id: 'id',
  clienteId: 'clienteId',
  tipoProducto: 'tipoProducto',
  mediosAsignados: 'mediosAsignados',
  ejesTematicos: 'ejesTematicos',
  parlamentarios: 'parlamentarios',
  frecuencia: 'frecuencia',
  formatoEntrega: 'formatoEntrega',
  fechaInicio: 'fechaInicio',
  fechaFin: 'fechaFin',
  montoMensual: 'montoMensual',
  moneda: 'moneda',
  estado: 'estado',
  notas: 'notas',
  fechaCreacion: 'fechaCreacion',
  fechaActualizacion: 'fechaActualizacion'
};

exports.Prisma.EjeTematicoScalarFieldEnum = {
  id: 'id',
  parentId: 'parentId',
  nombre: 'nombre',
  slug: 'slug',
  icono: 'icono',
  color: 'color',
  descripcion: 'descripcion',
  keywords: 'keywords',
  dimension: 'dimension',
  activo: 'activo',
  orden: 'orden',
  tipo: 'tipo'
};

exports.Prisma.EntregaScalarFieldEnum = {
  id: 'id',
  contratoId: 'contratoId',
  tipoBoletin: 'tipoBoletin',
  contenido: 'contenido',
  fechaProgramada: 'fechaProgramada',
  fechaEnvio: 'fechaEnvio',
  estado: 'estado',
  canal: 'canal',
  destinatarios: 'destinatarios',
  error: 'error',
  fechaCreacion: 'fechaCreacion'
};

exports.Prisma.EnvioReporteScalarFieldEnum = {
  id: 'id',
  reporteId: 'reporteId',
  canal: 'canal',
  destinatario: 'destinatario',
  estado: 'estado',
  enviadoEn: 'enviadoEn',
  error: 'error'
};

exports.Prisma.FuenteEstadoScalarFieldEnum = {
  id: 'id',
  medioId: 'medioId',
  url: 'url',
  tipoCheck: 'tipoCheck',
  etag: 'etag',
  lastModified: 'lastModified',
  fingerprint: 'fingerprint',
  ultimoValor: 'ultimoValor',
  ultimosIds: 'ultimosIds',
  homepageHtml: 'homepageHtml',
  ultimoCheck: 'ultimoCheck',
  ultimoCambio: 'ultimoCambio',
  totalChecks: 'totalChecks',
  totalCambios: 'totalCambios',
  checksSinCambio: 'checksSinCambio',
  horasPublicacion: 'horasPublicacion',
  horariosOptimos: 'horariosOptimos',
  frecuenciaBase: 'frecuenciaBase',
  frecuenciaActual: 'frecuenciaActual',
  activo: 'activo',
  fallosConsecutivos: 'fallosConsecutivos',
  error: 'error',
  responseTime: 'responseTime',
  estado: 'estado',
  capaActual: 'capaActual',
  ultimoCheckOk: 'ultimoCheckOk',
  ultimoHeadline: 'ultimoHeadline',
  ultimoTexto: 'ultimoTexto',
  ultimoMencion: 'ultimoMencion',
  totalHeadlines: 'totalHeadlines',
  totalTexto: 'totalTexto',
  totalMenciones: 'totalMenciones',
  strategyValid: 'strategyValid',
  strategyScrape: 'strategyScrape'
};

exports.Prisma.IndicadorScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  slug: 'slug',
  categoria: 'categoria',
  tipo: 'tipo',
  fuente: 'fuente',
  url: 'url',
  periodicidad: 'periodicidad',
  unidad: 'unidad',
  formatoNumero: 'formatoNumero',
  activo: 'activo',
  orden: 'orden',
  ejesTematicos: 'ejesTematicos',
  tier: 'tier',
  notas: 'notas',
  metodologia: 'metodologia',
  variables: 'variables',
  escalaMin: 'escalaMin',
  escalaMax: 'escalaMax',
  fechaCreacion: 'fechaCreacion',
  fechaActualizacion: 'fechaActualizacion'
};

exports.Prisma.IndicadorEvaluacionScalarFieldEnum = {
  id: 'id',
  indicadorId: 'indicadorId',
  fechaEvaluacion: 'fechaEvaluacion',
  valorCompuesto: 'valorCompuesto',
  valorTexto: 'valorTexto',
  escalaNivel: 'escalaNivel',
  puntuaciones: 'puntuaciones',
  observaciones: 'observaciones',
  fuentes: 'fuentes',
  evaluador: 'evaluador',
  confiable: 'confiable',
  fechaCreacion: 'fechaCreacion'
};

exports.Prisma.IndicadorValorScalarFieldEnum = {
  id: 'id',
  indicadorId: 'indicadorId',
  fecha: 'fecha',
  valor: 'valor',
  valorTexto: 'valorTexto',
  confiable: 'confiable',
  fechaCaptura: 'fechaCaptura',
  metadata: 'metadata'
};

exports.Prisma.JobScalarFieldEnum = {
  id: 'id',
  tipo: 'tipo',
  prioridad: 'prioridad',
  estado: 'estado',
  payload: 'payload',
  resultado: 'resultado',
  error: 'error',
  intentos: 'intentos',
  maxIntentos: 'maxIntentos',
  fechaCreacion: 'fechaCreacion',
  fechaInicio: 'fechaInicio',
  fechaFin: 'fechaFin',
  proximaEjecucion: 'proximaEjecucion',
  programa: 'programa'
};

exports.Prisma.KeywordScalarFieldEnum = {
  id: 'id',
  termino: 'termino',
  lenteId: 'lenteId',
  ejeId: 'ejeId',
  activo: 'activo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LenteScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  slug: 'slug',
  descripcion: 'descripcion',
  activo: 'activo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MedioScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  url: 'url',
  tipo: 'tipo',
  categoria: 'categoria',
  nivel: 'nivel',
  departamento: 'departamento',
  plataformas: 'plataformas',
  notas: 'notas',
  pais: 'pais',
  activo: 'activo',
  fechaCreacion: 'fechaCreacion',
  frecuenciaOverride: 'frecuenciaOverride',
  naturaleza: 'naturaleza',
  ambito: 'ambito',
  enfoque: 'enfoque',
  credibilidad: 'credibilidad',
  ultimaRevisionHumana: 'ultimaRevisionHumana',
  ultimoError: 'ultimoError',
  pesoInformativo: 'pesoInformativo'
};

exports.Prisma.MencionScalarFieldEnum = {
  id: 'id',
  personaId: 'personaId',
  medioId: 'medioId',
  titulo: 'titulo',
  texto: 'texto',
  url: 'url',
  fechaPublicacion: 'fechaPublicacion',
  fechaCaptura: 'fechaCaptura',
  tipoMencion: 'tipoMencion',
  temas: 'temas',
  reach: 'reach',
  verificado: 'verificado',
  fechaCreacion: 'fechaCreacion',
  enlaceActivo: 'enlaceActivo',
  fechaVerificacion: 'fechaVerificacion',
  textoCompleto: 'textoCompleto',
  comentariosCount: 'comentariosCount',
  comentariosResumen: 'comentariosResumen',
  sentimiento: 'sentimiento',
  tratamientoPeriodistico: 'tratamientoPeriodistico',
  confianzaClasificacion: 'confianzaClasificacion',
  preguntasFundamentales: 'preguntasFundamentales',
  esDuplicado: 'esDuplicado',
  mencionOriginalId: 'mencionOriginalId',
  mediosRelacionados: 'mediosRelacionados',
  eventoId: 'eventoId',
  coberturasAdicionales: 'coberturasAdicionales',
  deduplicacionLog: 'deduplicacionLog',
  intencionMedio: 'intencionMedio',
  ejeEstructuralId: 'ejeEstructuralId',
  evidenciaHtmlRuta: 'evidenciaHtmlRuta',
  evidenciaPngRuta: 'evidenciaPngRuta',
  evidenciaHashSha256: 'evidenciaHashSha256',
  evidenciaTimestamp: 'evidenciaTimestamp',
  evidenciaUrlOriginal: 'evidenciaUrlOriginal',
  evidenciaTamanoBytes: 'evidenciaTamanoBytes'
};

exports.Prisma.MencionLenteScalarFieldEnum = {
  id: 'id',
  mencionId: 'mencionId',
  lenteId: 'lenteId',
  createdAt: 'createdAt'
};

exports.Prisma.MencionTemaScalarFieldEnum = {
  id: 'id',
  mencionId: 'mencionId',
  ejeTematicoId: 'ejeTematicoId'
};

exports.Prisma.PersonaScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  camara: 'camara',
  departamento: 'departamento',
  partido: 'partido',
  partidoSigla: 'partidoSigla',
  tipo: 'tipo',
  cargoDirectiva: 'cargoDirectiva',
  email: 'email',
  fotoUrl: 'fotoUrl',
  activa: 'activa',
  periodo: 'periodo',
  fechaCreacion: 'fechaCreacion',
  fechaActualizacion: 'fechaActualizacion'
};

exports.Prisma.ReporteScalarFieldEnum = {
  id: 'id',
  tipo: 'tipo',
  personaId: 'personaId',
  fechaInicio: 'fechaInicio',
  fechaFin: 'fechaFin',
  resumen: 'resumen',
  pdfUrl: 'pdfUrl',
  enviado: 'enviado',
  fechaEnvio: 'fechaEnvio',
  totalMenciones: 'totalMenciones',
  sentimientoPromedio: 'sentimientoPromedio',
  temasPrincipales: 'temasPrincipales',
  fechaCreacion: 'fechaCreacion',
  totalComentarios: 'totalComentarios',
  sentimientoComentarios: 'sentimientoComentarios',
  enlacesRotos: 'enlacesRotos',
  contenido: 'contenido',
  clasificadores: 'clasificadores'
};

exports.Prisma.ReporteEjeScalarFieldEnum = {
  id: 'id',
  reporteId: 'reporteId',
  ejeTematico: 'ejeTematico',
  mencionCount: 'mencionCount',
  tratamientoTop: 'tratamientoTop',
  medioTop: 'medioTop',
  tendencia: 'tendencia',
  variacion: 'variacion'
};

exports.Prisma.ReporteSectorialScalarFieldEnum = {
  id: 'id',
  sector: 'sector',
  titulo: 'titulo',
  periodoInicio: 'periodoInicio',
  periodoFin: 'periodoFin',
  includeManana: 'includeManana',
  resumenEjecutivo: 'resumenEjecutivo',
  contenido: 'contenido',
  contenidoHtml: 'contenidoHtml',
  estado: 'estado',
  mencionCount: 'mencionCount',
  medioCount: 'medioCount',
  indiceExposicion: 'indiceExposicion',
  creadoEn: 'creadoEn',
  generadoEn: 'generadoEn',
  enviadoEn: 'enviadoEn'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires'
};

exports.Prisma.SugerenciaInteligenciaScalarFieldEnum = {
  id: 'id',
  tipo: 'tipo',
  datoPropuesto: 'datoPropuesto',
  confianza: 'confianza',
  estado: 'estado',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  procesadaEn: 'procesadaEn'
};

exports.Prisma.SuscriptorGratuitoScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  email: 'email',
  whatsapp: 'whatsapp',
  origen: 'origen',
  activo: 'activo',
  boletines: 'boletines',
  canal: 'canal',
  fechaSuscripcion: 'fechaSuscripcion'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  password: 'password',
  role: 'role',
  emailVerified: 'emailVerified',
  image: 'image',
  activo: 'activo',
  fechaCreacion: 'fechaCreacion'
};

exports.Prisma.VerificationTokenScalarFieldEnum = {
  identifier: 'identifier',
  token: 'token',
  expires: 'expires'
};

exports.Prisma.Cambio_marco_conceptualScalarFieldEnum = {
  id: 'id',
  marcoId: 'marcoId',
  campo: 'campo',
  valorAnterior: 'valorAnterior',
  valorNuevo: 'valorNuevo',
  razon: 'razon',
  creadoPor: 'creadoPor',
  creadoEn: 'creadoEn'
};

exports.Prisma.Eje_tematico_clienteScalarFieldEnum = {
  id: 'id',
  clienteId: 'clienteId',
  nombre: 'nombre',
  descripcion: 'descripcion',
  keywords: 'keywords',
  activo: 'activo',
  creadoPor: 'creadoPor',
  creadoEn: 'creadoEn',
  editadoPor: 'editadoPor',
  editadoEn: 'editadoEn'
};

exports.Prisma.Marco_conceptualScalarFieldEnum = {
  id: 'id',
  version: 'version',
  activa: 'activa',
  principios: 'principios',
  contextoInstitucional: 'contextoInstitucional',
  lineasEditoriales: 'lineasEditoriales',
  ejesInstitucionales: 'ejesInstitucionales',
  escalaTratamiento: 'escalaTratamiento',
  reglasDesambiguacion: 'reglasDesambiguacion',
  criteriosRelevancia: 'criteriosRelevancia',
  exclusionesEtica: 'exclusionesEtica',
  terminologiaPermitida: 'terminologiaPermitida',
  terminologiaProhibida: 'terminologiaProhibida',
  preguntasFundamentales: 'preguntasFundamentales',
  parametros: 'parametros',
  creadoPor: 'creadoPor',
  creadoEn: 'creadoEn',
  editadoPor: 'editadoPor',
  editadoEn: 'editadoEn'
};

exports.Prisma.RechazoCapturaScalarFieldEnum = {
  id: 'id',
  medioId: 'medioId',
  url: 'url',
  titulo: 'titulo',
  texto: 'texto',
  motivo: 'motivo',
  respuestaLLM: 'respuestaLLM',
  es_relevante: 'es_relevante',
  tratamiento: 'tratamiento',
  sentimiento: 'sentimiento',
  confianza: 'confianza',
  textoLen: 'textoLen',
  createdAt: 'createdAt'
};

exports.Prisma.Mencion_cliente_ejeScalarFieldEnum = {
  id: 'id',
  mencionId: 'mencionId',
  ejeClienteId: 'ejeClienteId',
  confianza: 'confianza'
};

exports.Prisma.UsoIAScalarFieldEnum = {
  id: 'id',
  modelo: 'modelo',
  fuente: 'fuente',
  promptTokens: 'promptTokens',
  completionTokens: 'completionTokens',
  totalTokens: 'totalTokens',
  costoUSD: 'costoUSD',
  medioId: 'medioId',
  mencionId: 'mencionId',
  detalles: 'detalles',
  createdAt: 'createdAt'
};

exports.Prisma.NotaRawScalarFieldEnum = {
  id: 'id',
  medioId: 'medioId',
  fuenteId: 'fuenteId',
  url: 'url',
  titulo: 'titulo',
  lead: 'lead',
  texto: 'texto',
  puntajeTriaje: 'puntajeTriaje',
  razonTriaje: 'razonTriaje',
  procesada: 'procesada',
  descartada: 'descartada',
  mencionesCreadas: 'mencionesCreadas',
  fechaCaptura: 'fechaCaptura',
  fechaProcesada: 'fechaProcesada'
};

exports.Prisma.FuenteErrorLogScalarFieldEnum = {
  id: 'id',
  fuenteId: 'fuenteId',
  medioId: 'medioId',
  nivel: 'nivel',
  tipoError: 'tipoError',
  estrategia: 'estrategia',
  url: 'url',
  statusCode: 'statusCode',
  mensaje: 'mensaje',
  detalle: 'detalle',
  responseTime: 'responseTime',
  resuelto: 'resuelto',
  fecha: 'fecha'
};

exports.Prisma.SystemLogScalarFieldEnum = {
  id: 'id',
  modulo: 'modulo',
  accion: 'accion',
  detalle: 'detalle',
  automatica: 'automatica',
  datos: 'datos',
  fecha: 'fecha'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};


exports.Prisma.ModelName = {
  Account: 'Account',
  AdminFeedback: 'AdminFeedback',
  AprendizajeSistema: 'AprendizajeSistema',
  CapturaLog: 'CapturaLog',
  Cliente: 'Cliente',
  Comentario: 'Comentario',
  Contrato: 'Contrato',
  EjeTematico: 'EjeTematico',
  Entrega: 'Entrega',
  EnvioReporte: 'EnvioReporte',
  FuenteEstado: 'FuenteEstado',
  Indicador: 'Indicador',
  IndicadorEvaluacion: 'IndicadorEvaluacion',
  IndicadorValor: 'IndicadorValor',
  Job: 'Job',
  Keyword: 'Keyword',
  Lente: 'Lente',
  Medio: 'Medio',
  Mencion: 'Mencion',
  MencionLente: 'MencionLente',
  MencionTema: 'MencionTema',
  Persona: 'Persona',
  Reporte: 'Reporte',
  ReporteEje: 'ReporteEje',
  ReporteSectorial: 'ReporteSectorial',
  Session: 'Session',
  SugerenciaInteligencia: 'SugerenciaInteligencia',
  SuscriptorGratuito: 'SuscriptorGratuito',
  User: 'User',
  VerificationToken: 'VerificationToken',
  cambio_marco_conceptual: 'cambio_marco_conceptual',
  eje_tematico_cliente: 'eje_tematico_cliente',
  marco_conceptual: 'marco_conceptual',
  RechazoCaptura: 'RechazoCaptura',
  mencion_cliente_eje: 'mencion_cliente_eje',
  UsoIA: 'UsoIA',
  NotaRaw: 'NotaRaw',
  FuenteErrorLog: 'FuenteErrorLog',
  SystemLog: 'SystemLog'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
